# Generated by Django 2.2.16 on 2020-09-11 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0004_auto_20200911_1951'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='projects/')),
                ('tools', models.CharField(max_length=200)),
                ('demo', models.URLField()),
                ('show_in_slider', models.BooleanField(default=False)),
            ],
        ),
    ]
