# Generated by Django 2.2.16 on 2020-09-14 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0006_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='slug',
            field=models.SlugField(default='e', max_length=200),
            preserve_default=False,
        ),
    ]
