# Generated by Django 2.2.16 on 2020-09-14 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0009_information'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='mini_about',
            field=models.TextField(default='s'),
            preserve_default=False,
        ),
    ]
