# Generated by Django 2.2.16 on 2020-12-01 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0015_auto_20201130_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatar/'),
        ),
    ]
