# Generated by Django 2.2.17 on 2020-12-03 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0017_auto_20201202_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='send_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
