# Generated by Django 2.2.16 on 2020-12-06 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0019_auto_20201203_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='send_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
