# Generated by Django 2.2.16 on 2020-12-22 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0020_auto_20201206_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='recaptcha',
            field=models.BooleanField(default=False),
        ),
    ]
