# Generated by Django 2.2.16 on 2020-12-22 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0022_auto_20201222_1655'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='recaptcha',
        ),
    ]
