# Generated by Django 4.2.7 on 2023-11-22 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0023_remove_message_recaptcha'),
    ]

    operations = [
        migrations.AddField(
            model_name='competence',
            name='order',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='education',
            name='order',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='experience',
            name='order',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='project',
            name='order',
            field=models.FloatField(default=1),
        ),
    ]
